export const researchTopics = [
  {
    slug: "artificial-intelligence",
    name: "Artificial Intelligence",
    shortDescription: "The broad field of building systems that perceive, reason, learn, and act in ways that support human goals.",
    overview: "Artificial intelligence brings together ideas from computer science, statistics, cognitive science, and many application domains. It is less a single technique than a family of approaches for turning observations, objectives, and constraints into useful decisions or generated outputs.",
    whatItIs: "AI studies computational systems that perform tasks associated with intelligent behavior, including perception, planning, language use, prediction, and decision-making. Some systems rely on explicit rules; others learn representations and policies from data.",
    howItWorks: "An AI system usually combines a task definition, data or observations, a model, and an evaluation procedure. During training or design, the system is adjusted against an objective. During use, it processes new inputs and produces predictions, actions, rankings, or content, often with safeguards and human oversight.",
    keyConcepts: ["Representation and abstraction", "Inference and prediction", "Planning and search", "Learning objectives", "Evaluation and robustness", "Human-AI interaction"],
    researchQuestions: ["How can systems generalize reliably beyond their training distribution?", "How should capability, safety, fairness, and usefulness be measured together?", "How can people understand, contest, and effectively collaborate with AI decisions?", "Which combinations of symbolic and statistical methods best support dependable reasoning?"],
    applications: ["Scientific discovery and literature analysis", "Assistive technologies", "Robotics and autonomous systems", "Decision support in health and public services", "Recommendation and information retrieval"],
    related: ["Machine Learning", "Generative AI", "Reinforcement Learning"],
    searchQuery: "artificial intelligence reasoning learning",
  },
  {
    slug: "machine-learning",
    name: "Machine Learning",
    shortDescription: "Methods for learning patterns from data so models can predict, classify, rank, or choose actions.",
    overview: "Machine learning treats experience as a source of model improvement. Researchers study how data, inductive assumptions, objectives, and optimization interact, with an emphasis on performance that holds up on new examples rather than only on the training set.",
    whatItIs: "Machine learning is the study of algorithms that infer useful structure from examples or feedback. Supervised learning uses labeled outcomes, unsupervised learning looks for structure without labels, and self-supervised learning creates training signals from the data itself.",
    howItWorks: "A typical workflow defines a target, prepares data, selects a model family, optimizes parameters, and evaluates on held-out or carefully designed test data. Deployment adds monitoring for drift, calibration, privacy, latency, and failures that a benchmark may not reveal.",
    keyConcepts: ["Training and generalization", "Features and representations", "Loss functions and optimization", "Regularization", "Data distribution shift", "Calibration and uncertainty"],
    researchQuestions: ["How can models learn from less labeled data and fewer compute resources?", "How should evaluation expose rare, costly, or socially consequential failures?", "Can models communicate uncertainty in ways people can use?", "How can learning systems remain useful as their environment changes?"],
    applications: ["Forecasting and anomaly detection", "Medical and environmental monitoring", "Search and recommendation", "Fraud and quality-control systems", "Personalized education"],
    related: ["Deep Learning", "Artificial Intelligence", "Reinforcement Learning"],
    searchQuery: "machine learning generalization optimization",
  },
  {
    slug: "deep-learning",
    name: "Deep Learning",
    shortDescription: "Representation learning with multilayer neural networks, applied across language, vision, speech, and science.",
    overview: "Deep learning uses compositions of parameterized transformations to learn multiple levels of representation. Its progress comes from the interaction of architectures, large datasets, hardware, optimization methods, and increasingly careful evaluation.",
    whatItIs: "A deep neural network is a model with many layers whose parameters are learned from data. Layers can transform raw inputs into features useful for a task, reducing the need to specify every relevant pattern by hand.",
    howItWorks: "Inputs pass forward through a network to produce an output. A loss compares that output with a target, and gradient-based optimization adjusts the parameters. At scale, pretraining, transfer learning, augmentation, and distributed computation make it possible to reuse representations across tasks.",
    keyConcepts: ["Backpropagation and gradient descent", "Convolution and attention", "Pretraining and transfer learning", "Embeddings", "Scaling and compute", "Overfitting and regularization"],
    researchQuestions: ["Why do large models generalize despite interpolation of their training data?", "How can training become more efficient in data, energy, and hardware?", "What representations are learned, and how stable are they under shifts?", "How can deep models incorporate structure, constraints, or reliable memory?"],
    applications: ["Image and speech recognition", "Protein and materials modeling", "Document understanding", "Autonomous perception", "Generative media tools"],
    related: ["Machine Learning", "Transformers", "Computer Vision"],
    searchQuery: "deep learning neural networks representation learning",
  },
  {
    slug: "large-language-models",
    name: "Large Language Models",
    shortDescription: "Large neural language models that learn broad linguistic patterns and can be adapted for many text tasks.",
    overview: "Large language models are trained on extensive text collections to predict and model sequences of tokens. Their capabilities emerge from scale, architecture, data mixture, optimization, and post-training, while their limitations include unreliable factuality, bias, and sensitivity to context.",
    whatItIs: "An LLM is a parameterized model that assigns probabilities to token sequences and uses those probabilities to generate or score text. Post-training can make it more useful for dialogue, instruction following, coding, or specialized domains.",
    howItWorks: "Text is tokenized, transformed into vectors, and processed through repeated layers, commonly using self-attention. Pretraining learns statistical regularities; supervised examples and preference-based methods can shape behavior afterward. Inference then generates tokens step by step under a decoding strategy.",
    keyConcepts: ["Tokenization and embeddings", "Pretraining and scaling laws", "Instruction tuning", "Alignment and preference optimization", "Context windows", "Factuality and calibration"],
    researchQuestions: ["What explains sudden or uneven capability changes with scale?", "How can models cite evidence and distinguish knowledge from uncertainty?", "How should data provenance, memorization, and privacy be evaluated?", "Which evaluations measure useful reasoning rather than benchmark familiarity?"],
    applications: ["Writing and coding assistance", "Document classification and extraction", "Tutoring and language learning", "Research support", "Conversational interfaces"],
    related: ["Transformers", "Natural Language Processing", "Retrieval-Augmented Generation"],
    searchQuery: "large language models evaluation alignment",
  },
  {
    slug: "transformers",
    name: "Transformers",
    shortDescription: "Attention-based neural architectures that model relationships among elements in sequences and other structured inputs.",
    overview: "Transformers changed sequence modeling by making attention a central operation rather than processing tokens only in order. Their flexible architecture now supports language, images, audio, code, multimodal data, and scientific representations.",
    whatItIs: "A Transformer is a neural architecture built around attention, which lets each element use information from other elements. Blocks typically combine attention, nonlinear transformations, residual connections, and normalization.",
    howItWorks: "Inputs become vectors with information about position or structure. Queries, keys, and values determine which relationships matter for each representation, while stacked blocks refine the result. Training objectives vary from predicting missing or next elements to matching multiple modalities.",
    keyConcepts: ["Self-attention", "Queries, keys, and values", "Positional information", "Encoder and decoder stacks", "Causal masking", "Efficient and sparse attention"],
    researchQuestions: ["How can attention handle long contexts without quadratic cost?", "When do attention patterns correspond to meaningful computation?", "How should architecture change for streams, graphs, images, or scientific data?", "What makes a Transformer robust to noisy or adversarial inputs?"],
    applications: ["Language modeling and translation", "Vision and video understanding", "Speech and music processing", "Code generation", "Multimodal scientific models"],
    related: ["Large Language Models", "Deep Learning", "Natural Language Processing"],
    searchQuery: "transformer architecture self attention",
  },
  {
    slug: "natural-language-processing",
    name: "Natural Language Processing",
    shortDescription: "The study of computational methods for understanding, generating, and interacting through human language.",
    overview: "Natural language processing connects linguistic structure with statistical and neural computation. The field covers everything from information extraction and translation to discourse, pragmatics, evaluation, and the social contexts in which language technologies operate.",
    whatItIs: "NLP develops systems that analyze or produce language in text and speech. It must contend with ambiguity, context, variation across communities, changing usage, and the fact that meaning often depends on the world beyond the words.",
    howItWorks: "Systems may tokenize and represent language, identify structure, retrieve evidence, infer labels, or generate responses. Modern pipelines often combine pretrained models with task data, retrieval, tools, and human review, with evaluation designed for the intended users and domain.",
    keyConcepts: ["Syntax and semantics", "Discourse and pragmatics", "Language representation", "Information extraction", "Machine translation", "Grounding and evaluation"],
    researchQuestions: ["How can systems represent meaning across languages, dialects, and domains?", "How should open-ended generation be evaluated for usefulness and truthfulness?", "Can language models ground claims in verifiable context?", "How can communities participate in defining language technology quality?"],
    applications: ["Search and question answering", "Translation and accessibility", "Document analysis", "Speech interfaces", "Public-health and scientific text mining"],
    related: ["Large Language Models", "Transformers", "Retrieval-Augmented Generation"],
    searchQuery: "natural language processing language understanding",
  },
  {
    slug: "retrieval-augmented-generation",
    name: "Retrieval-Augmented Generation",
    shortDescription: "Systems that retrieve relevant external information before generating an answer or other response.",
    overview: "Retrieval-augmented generation, or RAG, addresses a central limitation of generative models: useful knowledge may be missing, stale, or difficult to verify inside model parameters. RAG makes the evidence path explicit by connecting retrieval with generation.",
    whatItIs: "A RAG system searches a collection for passages, records, or documents relevant to a query and supplies them to a language model as context. The generator can then produce an answer constrained by, or at least informed by, those retrieved sources.",
    howItWorks: "Documents are collected, segmented, indexed, and represented for retrieval. A query selects candidates through lexical, vector, or hybrid search; reranking can improve relevance. The model receives selected context and generates a response, ideally with citations and checks for unsupported claims.",
    keyConcepts: ["Chunking and indexing", "Dense and sparse retrieval", "Reranking", "Context selection", "Grounded generation", "Attribution and faithfulness"],
    researchQuestions: ["How can retrieval find the right evidence when queries and documents use different language?", "How should systems detect missing, conflicting, or low-quality sources?", "What evaluation separates retrieval errors from generation errors?", "How can citations be made complete, precise, and useful to readers?"],
    applications: ["Research literature assistants", "Enterprise knowledge search", "Technical support", "Legal and policy document analysis", "Evidence-aware question answering"],
    related: ["Large Language Models", "Natural Language Processing", "Information Retrieval"],
    searchQuery: "retrieval augmented generation grounding factuality",
  },
  {
    slug: "generative-ai",
    name: "Generative AI",
    shortDescription: "Models that produce new text, images, audio, video, code, or structured outputs from learned distributions.",
    overview: "Generative AI learns patterns in data and uses them to synthesize new outputs. The research frontier includes controllability, quality, provenance, interaction design, evaluation, and the effects of deploying generators in creative and knowledge work.",
    whatItIs: "Generative models estimate or approximate a data distribution so they can sample, complete, transform, or edit examples. They may use autoregressive prediction, diffusion, latent-variable models, or other approaches.",
    howItWorks: "Training exposes a model to examples and an objective for reconstructing, predicting, denoising, or matching data. At generation time, conditioning information and a sampling process guide output creation. Product systems add filters, editing controls, retrieval, and human review.",
    keyConcepts: ["Autoregressive modeling", "Diffusion and denoising", "Latent representations", "Conditioning and control", "Data provenance", "Quality and safety evaluation"],
    researchQuestions: ["How can creators control structure, style, and factual content together?", "How should synthetic data and generated media be identified and governed?", "What training data is memorized, and how can unwanted reproduction be reduced?", "How can evaluation reflect originality, usefulness, and downstream impact?"],
    applications: ["Design and creative production", "Code and document drafting", "Simulation and synthetic data", "Education and accessibility", "Scientific hypothesis generation"],
    related: ["Artificial Intelligence", "Large Language Models", "Computer Vision"],
    searchQuery: "generative artificial intelligence diffusion models evaluation",
  },
  {
    slug: "computer-vision",
    name: "Computer Vision",
    shortDescription: "Methods for enabling computers to interpret images, video, 3D scenes, and visual measurements.",
    overview: "Computer vision turns visual signals into descriptions, measurements, predictions, and actions. Research spans low-level image formation, recognition, geometry, multimodal learning, and the reliability of systems used in varied environments.",
    whatItIs: "Computer vision studies how machines can infer objects, regions, motion, depth, identity, and events from visual data. The problem is inherently ambiguous: a 2D image can support multiple plausible explanations of a 3D world.",
    howItWorks: "A vision pipeline may preprocess pixels, learn visual representations, detect or segment entities, estimate geometry, and combine evidence across time or modalities. Models are trained with labels, self-supervised signals, synthetic data, or physical and geometric constraints.",
    keyConcepts: ["Image representation", "Classification and detection", "Segmentation", "Three-dimensional geometry", "Video and tracking", "Vision-language learning"],
    researchQuestions: ["How can visual models understand uncommon objects and changing environments?", "How should systems represent uncertainty in safety-critical perception?", "Can models learn physical and causal structure from observation?", "How do dataset bias and camera context affect real-world performance?"],
    applications: ["Medical imaging", "Robotics and navigation", "Remote sensing", "Manufacturing inspection", "Accessibility and assistive perception"],
    related: ["Deep Learning", "Transformers", "Generative AI"],
    searchQuery: "computer vision visual representation learning",
  },
  {
    slug: "reinforcement-learning",
    name: "Reinforcement Learning",
    shortDescription: "Learning to make sequential decisions through interaction, feedback, and long-term objectives.",
    overview: "Reinforcement learning studies agents that choose actions in an environment and learn from resulting rewards or observations. It is especially useful when decisions change what information and opportunities become available later.",
    whatItIs: "An RL problem describes states, actions, transitions, and a reward or utility signal. The agent seeks a policy that balances immediate outcomes with future return, often under uncertainty and incomplete knowledge.",
    howItWorks: "An agent explores by taking actions, observes consequences, and updates a value estimate or policy. Algorithms may learn from a model of the environment, direct experience, demonstrations, or feedback from humans. Simulation and offline data can reduce costly or unsafe real-world exploration.",
    keyConcepts: ["States, actions, and rewards", "Policies and value functions", "Exploration and exploitation", "Credit assignment", "Planning and model learning", "Offline and safe RL"],
    researchQuestions: ["How can agents learn safely when exploration has real costs?", "How should rewards encode goals without inviting unintended behavior?", "Can policies transfer across tasks, environments, and embodiments?", "How can humans provide feedback that remains reliable at scale?"],
    applications: ["Robotics and control", "Resource and traffic management", "Personalized tutoring", "Operations and scheduling", "Scientific experiment design"],
    related: ["Machine Learning", "Artificial Intelligence", "Deep Learning"],
    searchQuery: "reinforcement learning decision making exploration",
  },
];

export const topicBySlug = Object.fromEntries(researchTopics.map((topic) => [topic.slug, topic]));
